version: '3'

tasks:
  serve:
    desc: Serve the website locally on port 8080
    cmds:
      - python3 -m http.server 8080
    dir: '{{.ROOT_DIR}}'

  serve:3000:
    desc: Serve the website locally on port 3000
    cmds:
      - python3 -m http.server 3000
    dir: '{{.ROOT_DIR}}'
